apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: your-docker-image:tag
          ports:
            - containerPort: 8080
          env:
            - name: JAR_FILE
              value: "orders-service-example-0.0.1-SNAPSHOT.jar"
            - name: APP_ARGS
              value: "abfdca1dd319f453b98685429ff4d417-1896863135.us-east-1.elb.amazonaws.com a41213400f45a4f25864f6162eaea70c-1625216118.us-east-1.elb.amazonaws.com a81afd56394fc4a9d890d759051c666e-1416510889.us-east-1.elb.amazonaws.com"
